name: CI Klab

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache do Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Dar permissão de execução
      run: chmod +x gradlew

    - name: Compilar e Testar
      run: ./gradlew build
